[package]
name = "witness-3ds"
version = "0.1.0"
edition = "2021"

[dependencies]
ctru-rs = { git = "https://github.com/rust3ds/ctru-rs" }
gameplay = { path = "../gameplay" }

[package.metadata.cargo-3ds]
romfs_dir = "romfs"
